# Pin the suspend mode on device-tree (arm64) machines.
#
# The kernel exposes the modes it supports in /sys/power/mem_sleep and picks one
# by default. On arm64 laptops it picks "deep", which maps to PSCI
# SYSTEM_SUSPEND -- that commonly suspends and never resumes, leaving the machine
# dark and unresponsive. Suspend-to-idle is the path that works.
#
# The mode is derived from what this kernel actually offers rather than
# hardcoded, so the script is a no-op on machines where there is no choice to
# make, and on ACPI machines where the kernel default is already the right one.
#
# Applied as a tmpfiles rule rather than a mem_sleep_default= kernel parameter so
# it survives a bootloader change and does not depend on the cmdline, which on
# these machines lives in a hand-written boot entry alongside several other
# platform-critical parameters.

mem_sleep_mode="$(swarmarchy-hw-mem-sleep-preferred)"

if [[ -n $mem_sleep_mode ]]; then
  sudo tee /etc/tmpfiles.d/99-mem-sleep.conf >/dev/null <<EOF
# Generated by swarmarchy: install/config/hardware/suspend-mode.sh
# This kernel defaults to PSCI SYSTEM_SUSPEND ("deep"), which does not resume
# reliably on arm64 laptops. Pin suspend-to-idle instead.
w /sys/power/mem_sleep - - - - $mem_sleep_mode
EOF

  sudo systemd-tmpfiles --create /etc/tmpfiles.d/99-mem-sleep.conf
fi
