run_logged $SWARMARCHY_INSTALL/config/config.sh
run_logged $SWARMARCHY_INSTALL/config/system-files.sh
run_logged $SWARMARCHY_INSTALL/config/theme.sh
run_logged $SWARMARCHY_INSTALL/config/branding.sh
run_logged $SWARMARCHY_INSTALL/config/git.sh
run_logged $SWARMARCHY_INSTALL/config/gpg.sh
run_logged $SWARMARCHY_INSTALL/config/xcompose.sh
run_logged $SWARMARCHY_INSTALL/config/mise-work.sh
run_logged $SWARMARCHY_INSTALL/config/fix-powerprofilesctl-shebang.sh
run_logged $SWARMARCHY_INSTALL/config/docker.sh
run_logged $SWARMARCHY_INSTALL/config/mimetypes.sh
run_logged $SWARMARCHY_INSTALL/config/user-dirs.sh
run_logged $SWARMARCHY_INSTALL/config/nautilus-python.sh
run_logged $SWARMARCHY_INSTALL/config/localdb.sh
run_logged $SWARMARCHY_INSTALL/config/walker-elephant.sh
run_logged $SWARMARCHY_INSTALL/config/sudoless-asdcontrol.sh
run_logged $SWARMARCHY_INSTALL/config/input-group.sh
run_logged $SWARMARCHY_INSTALL/config/swarmarchy-ai-skill.sh
run_logged $SWARMARCHY_INSTALL/config/pi.sh
run_logged $SWARMARCHY_INSTALL/config/swarmarchy-toggles.sh
run_logged $SWARMARCHY_INSTALL/config/kernel-modules-hook.sh
run_logged $SWARMARCHY_INSTALL/config/powerprofilesctl-rules.sh
run_logged $SWARMARCHY_INSTALL/config/wifi-powersave-rules.sh

run_logged $SWARMARCHY_INSTALL/config/hardware/network.sh
run_logged $SWARMARCHY_INSTALL/config/hardware/set-wireless-regdom.sh
run_logged $SWARMARCHY_INSTALL/config/hardware/fix-fkeys.sh
run_logged $SWARMARCHY_INSTALL/config/hardware/bluetooth.sh
run_logged $SWARMARCHY_INSTALL/config/hardware/printer.sh
run_logged $SWARMARCHY_INSTALL/config/hardware/usb-autosuspend.sh
run_logged $SWARMARCHY_INSTALL/config/hardware/suspend-mode.sh
run_logged $SWARMARCHY_INSTALL/config/hardware/ignore-power-button.sh
run_logged $SWARMARCHY_INSTALL/config/hardware/nvidia.sh
run_logged $SWARMARCHY_INSTALL/config/hardware/vulkan.sh

run_logged $SWARMARCHY_INSTALL/config/hardware/lenovo/fix-yoga-pro7-bass-speakers.sh

run_logged $SWARMARCHY_INSTALL/config/hardware/fix-bcm43xx.sh
run_logged $SWARMARCHY_INSTALL/config/hardware/fix-surface-keyboard.sh
run_logged $SWARMARCHY_INSTALL/config/hardware/fix-yt6801-ethernet-adapter.sh
run_logged $SWARMARCHY_INSTALL/config/hardware/fix-synaptic-touchpad.sh
run_logged $SWARMARCHY_INSTALL/config/hardware/fix-tuxedo-backlight.sh
