# Sway window border colors (generated by swarmarchy-theme-set from this template).
# Included by config/sway/config after the defaults, so it overrides the
# placeholder colors in default/sway/appearance.conf.
#
# Order: border  background  text  indicator  child_border
# With `default_border pixel`, child_border is the color that actually shows.

client.focused          {{ accent }}  {{ accent }}  {{ background }}  {{ accent }}  {{ accent }}
client.focused_inactive {{ color0 }}  {{ color0 }}  {{ foreground }}  {{ color0 }}  {{ color0 }}
client.unfocused        {{ color0 }}  {{ color0 }}  {{ foreground }}  {{ color0 }}  {{ color0 }}
client.urgent           {{ color1 }}  {{ color1 }}  {{ background }}  {{ color1 }}  {{ color1 }}
